### ISSUE TITLE
Number of iterations of OSLOM

### ISSUE THREAD

**Issue by sean-bam** [cytoscape/cy-community-detection#15]
Hi all, I was exploring your tool in cytoscape and am impressed with its ease of use. One question that I have is how many iterations of OSLOM are run by default? Looking at the [OSLOM documentation](http://www.oslom.org/code/ReadMe.pdf), the default is 10 (-r flag), but I don't see that mentioned anywhere in your documentation. Thanks for clarifying!

**Comment by coleslaw481** [comment]
Thank you. You are correct we do not pass the `-r` flag into OSLOM so it should be using the default of `10` 

If needed we can expose this parameter. Let me know.

**Comment by sean-bam** [comment]
Excellent, thanks for clarifying! I don't think there is an immediate need to expose this parameter, but thought it best to double check.
